version: 2.1

orbs:
  zulip: ponylang/zulip@1

jobs:
  build-missing-docs:
    docker:
      - image: ponylang/main.actor-ci:standard
    steps:
      - checkout
      - run: bash build-missing-docs.sh
      - zulip/status

workflows:
  version: 2.1
  commit:
    jobs:
      - build-missing-docs:
          context: org-global

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-missing-docs:
          context: org-global

